name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. DESCARGAR EL CÓDIGO
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. PREPARAR EL ENTORNO FRONTEND
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Puedes cambiarlo si tu proyecto usa Node 20

      # 3. INSTALAR DEPENDENCIAS
      - name: Install dependencies
        run: npm install

      # 4. CORRER LOS TESTS Y GENERAR COBERTURA
      # --no-watch es vital para que el CI no se quede colgado esperando
      - name: Run tests with coverage
        run: npm run test -- --no-watch --code-coverage 

      # 5. ESCANEAR CON SONARCLOUD
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=jhosue-pstr_All-In-One-Frontend
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/**/lcov.info